version: '3.8'

services:

  mysql_db:
    image: mysql:latest
    networks: 
       - app-tier
    volumes:
       - ./mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE      
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234 

  mongo_db:
    image: mongo:latest
    restart: unless-stopped    
    networks: 
       - app-tier
    volumes:
       - ./mongo/db:/data/db
    ports:
      - "27017:27017"

  redis:
    image: "redis:alpine"
    networks: 
       - app-tier    

  python_app:
    build:
      context: .
      dockerfile: ./flask/Dockerfile
    ports:
      - "5000:5000"    
    links:
      - mongo_db:mongo_db     
      - mysql_db:mysql_db             
    depends_on:
      - mysql_db
      - mongo_db
      - redis
    networks:
      - app-tier
    restart: always      
    volumes:
       - ./flask/web:/app

  java_app:
    build:
      context: .
      dockerfile: ./java/docker-spring-boot/Dockerfile
    ports:
      - "8080:8080"    
    volumes:
       - ./java/docker-spring-boot/target:/opt/app
    links:
      - mongo_db:mongo_db       
    depends_on:
      - mysql_db
      - mongo_db
      - redis
    networks:
      - app-tier
    restart: always        


networks:
  app-tier:
    driver: bridge
